// @file types/changelog.ts
// @description Changelog entry types for the Aiflo platform. Used for the changelog page and release notes.

export type ChangelogEntry = {
  id: string;
  version: string;
  date: string;
  title: string;
  highlights: string[]; // Bullet points for summary
  details?: string; // Optional legacy description
  markdownContent?: string; // Full markdown content for the changelog
  image?: string; // Optional main image path
  images?: string[]; // Optional array of images for the changelog
  icon?: string; // Optional Lucide icon name
};

export const changelogEntries: ChangelogEntry[] = [
  {
    id: "2025-05-05-initial-release",
    version: "0.0",
    date: "2025-05-05",
    title: "Initial Release: Multi-LLM Support, Google Auth, and Subscription",
    highlights: [
      "Support for multiple LLMs: Gemini 2.5 Flash, GPT-4.1, Claude Sonnet 4, Mistral Large 2411, Grok 3 Mini Beta, Perplexity Sonar, DeepSeek Chat V3 0324, Llama 4 Maverick",
    ],
    markdownContent: `### Welcome to the first public release!

**What's new:**

- **Multiple LLMs supported:**

  - Gemini 2.5 Flash
  - GPT-4.1
  - Claude Sonnet 4
  - Mistral Large 2411
  - Grok 3 Mini Beta
  - Perplexity Sonar
  - DeepSeek Chat V3 0324
  - Llama 4 Maverick

- **Google authentication** for quick and secure sign-in

- **$12/month subscription** for unlimited access (fair usage policy applies)

---

> **Coming soon:** Image generation support with GPT-Image-1!

Thank you for being an early user.`,
    icon: "layers",
  },
  {
    id: "2025-05-30-gpt-image-1-support",
    version: "0.1",
    date: "2025-05-30",
    title: "Image Generation with GPT-Image-1 & 50 Credits for Basic Members",
    highlights: ["Support for image generation using GPT-Image-1"],
    markdownContent: `### New: Image Generation with GPT-Image-1

You can now generate images directly in Aiflo using **GPT-Image-1**!

- Try out the new image generation feature in your chats.
- All basic subscription members receive **50 free credits** to get started.

#### Here is an image of a cute cat generated by GPT-Image-1 with [AiFlo](https://aiflo.space)

![A cute cat generated by GPT-Image-1 with AiFlo](https://fklzjkhihskgqmtgksdn.supabase.co/storage/v1/object/public/c/conversationid/42aac343-3c6d-4091-b15b-cbeb3c6875db/2eb0bbcc-c46e-49b2-92fc-df2ae3c3a3ef.webp)

---

> **We're excited to see what you are going to create!**
`,
    image:
      "https://fklzjkhihskgqmtgksdn.supabase.co/storage/v1/object/public/c/conversationid/42aac343-3c6d-4091-b15b-cbeb3c3a3ef.webp",
    icon: "image",
  },
];

// Ensure this is a module
export {};
